const sharp = require('sharp')
const fs = require('fs')
const W = 2732, H = 2732
const logo = fs.readFileSync('assets-icon.png')
const badge = Buffer.from(`<svg width="${W}" height="${H}"><rect width="100%" height="100%" fill="#06060a"/></svg>`)
sharp(badge)
  .composite([{ input: logo, left: Math.round(W * 0.35), top: Math.round(H * 0.36) }])
  .png()
  .toFile('assets-splash.png')
  .then(() => fs.copyFileSync('assets-icon.png', 'assets-logo.png'))
  .then(() => console.log('splash + logo OK'))
  .catch((e) => { console.error('ERR', e.message); process.exit(1) })
